### ISSUE TITLE
The C++98 version does not compile on a C++98 compiler.  Exotic hardware needs that.

### ISSUE THREAD

**Issue by ajohnston33** [msharov/ustl#67]
I am working on a digital signal processor with an Open64 compiler from 2013.   Can you provide an old c++98 version of your library?

**Comment by msharov** [comment]
c++11 support first appeared in version 2.0; all earlier releases are still available on the project releases page.

The current release of uSTL is still supposed to work with a c++98 compiler, so if you are having errors on c++11 incompatibilites, please report them so that they could be fixed.

**Comment by msharov** [comment]
Please check if you are still unable to compile with the latest v2.5 release.

**Comment by ajohnston33** [comment]
Because I am cross compiling to a platform that has no development environment, I was trying to configure the project manually.  While I thought I had the two feature test macros set correctly, it seems I missed something.  I would gladly continue testing for you if you want to provide a configuration file that should work on C++98 embedded platforms.  Otherwise, you can close this ticket and I will look at using the pre-2.0 release.  I really appreciate your help.

**Comment by msharov** [comment]
While I do not intend to support embedded platforms, I can probably explain what you are missing if you post the error log. Using an earlier release is not necessarily going to help you.

**Comment by ajohnston33** [comment]
With the following config:
`#define STDC_HEADERS 1
#define STDUNIX_HEADERS 1
#define WITHOUT_LIBSTDCPP 1
#define HAVE_STDINT_H 1
#ifndef BYTE_ORDER
#define LITTLE_ENDIAN	USTL_LITTLE_ENDIAN
#define BIG_ENDIAN		USTL_BIG_ENDIAN
#define BYTE_ORDER		USTL_BYTE_ORDER
#endif`

I get:
`ustl/ulimits.h(25): error: 'constexpr' does not name a type`

`In file included from C:/src/.../ustl/uutility.h:12,
                 from C:/src/.../ustl/ualgobase.h:8,
                 from C:/src/.../ustl/cmemlink.h:8,
                 from C:/src/.../ustl/memlink.h:8,
                 from C:/src/.../ustl/memblock.h:8,
                 from C:/src/.../ustl/uvector.h:8,`

**Comment by msharov** [comment]
See config.h, line 58. There is some preprocessor code to enable c++11 there. Apparently your compiler reports that it is capable of c++11 (by defining __cplusplus to >201103). You can remove that section and replace it with #undef HAVE_CPP11

**Comment by ajohnston33** [comment]
With your encouragement I did manage to hack together a working config.h for c++98.  Thanks!
