### ISSUE TITLE
Version 2.3 build issues

### ISSUE THREAD

**Issue by dfateyev** [msharov/ustl#49]
Also I cannot build v2.3 on Fedora 23 amd64 (gcc 5.3.1):
```
    Compiling unew.cc ...
g++ -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -Wall -Wextra -Woverloaded-virtual -Wpointer-arith -Wshadow -Wredundant-decls -Wcast-qual -std=c++14  -I/home/mock/rpmbuild/BUILDROOT/ustl-2.3-1.fc23.denf.x86_64/usr/include -fPIC -MMD -MT "unew.s .o/unew.o" -o .o/unew.o -c unew.cc
unew.cc:20:1: error: expected '}' at end of input
 }
 ^
Makefile:50: recipe for target '.o/unew.o' failed
make: *** [.o/unew.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from sistream.h:7:0,
                 from ofstream.h:7,
                 from ofstream.cc:6:
mistream.h: In member function 'void ustl::ustl::istream::iread(T&)':
mistream.h:235:43: error: must #include <typeinfo> before using typeid
     if (!verify_remaining ("read", typeid(v).name(), sizeof(T)))
                                           ^
In file included from sistream.h:8:0,
                 from ofstream.h:7,
                 from ofstream.cc:6:
ustring.h: At global scope:
ustring.h:54:21: error: 'reverse_iterator' in namespace 'ustl' does not name a template type
     typedef ::ustl::reverse_iterator<iterator>  reverse_iterator;
                     ^
ustring.h:55:21: error: 'reverse_iterator' in namespace 'ustl' does not name a template type
     typedef ::ustl::reverse_iterator<const_iterator> const_reverse_iterator;
                     ^
ustring.h:83:12: error: invalid use of template-name 'ustl::ustl::reverse_iterator' without an argument list
     inline reverse_iterator rbegin (void)   { return reverse_iterator (end()); }
            ^
ustring.h:84:10: error: 'const_reverse_iterator' does not name a type
```

**Comment by msharov** [comment]
The unew.cc failure was fixed by commit e323d78fdcc4aeb2a81347b65577b791d4dedee0. That could also be the cause of the failure to find reverse_iterator. Please retry with the current branch.

These failures only occur when using --with-libstdc++ option to configure, enabling the use of both uSTL and libstdc++ together. This configuration is rarely tested and thus more buggy than the usual one. It would probably be best to eliminate it from future uSTL releases.

**Comment by dfateyev** [comment]
Looks like fixed now with the GCC version above (5.3.1).
I'm also going to check with other versions to be 100% sure.

**Comment by dfateyev** [comment]
With an older GCC (4.8.5, RHEL/CentOS 7) it throws:
```
echo "    Compiling memblock.cc ..."
    Compiling memblock.cc ...
g++ -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -Wall -Wextra -Woverloaded-virtual -Wpointer-arith -Wshadow -Wredundant-decls -Wcast-qual -std=c++11  -I/root/rpmbuild/BUILDROOT/ustl-2.4-1.el7.centos.x86_64/usr/include -fPIC -MMD -MT "memblock.s .o/memblock.o" -o .o/memblock.o -c memblock.cc
ustring.cc:16:32: error: redeclaration 'ustl::string::npos' differs in 'constexpr'
 const string::pos_type string::npos;
                                ^
In file included from ustring.cc:6:0:
ustring.h:58:37: error: from previous declaration 'ustl::string::npos'
     static constexpr const pos_type npos = INT_MAX; ///< Value that means the end of string.
                                     ^
ustring.cc:16:32: error: declaration of 'constexpr const pos_type ustl::string::npos' outside of class is not definition [-fpermissive]
 const string::pos_type string::npos;
                                ^
make: *** [.o/ustring.o] Error 1
```
Although it's not crucial since I can keep 2.2 - 2.3 in RHEL EPEL.
But if possible it would be good to get it fixed too..

**Comment by msharov** [comment]
Ok, fixed in 7c8e0111a8d6aa73ec37c9ad640b283da3d2244b.
